### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by xuwuzhou** [Mitchell-Lee-93/kitti-lego-loam#1]
I have some questions;
first ,do you delete the IMU information?
second,last week I use the repo test the kitti raw data(=sequence00+IMU),but unfortunately,the result is not good ,have you tested the 00 sequence ever?
![图片](https://user-images.githubusercontent.com/44218507/71641717-61e3cb00-2cdb-11ea-880e-49d04764e3d7.png)

**Comment by xuwuzhou** [comment]
by the way ,I use the tool "kitti2bag" to transform the raw kitti data to bag

**Comment by Mitchell-Lee-93** [comment]
[
![123](https://user-images.githubusercontent.com/56542570/71656732-e425cb00-2d7f-11ea-86a3-4d810f7f9f4c.png)
](url)

Hello xuwuzhou
This is the result of kitti-lego-loam of 00 sequence with only lidar data(no imu, no loop closure) 
And I haven't made any changes to the IMU part.
Would you try without IMU and see what you get?

**Comment by xuwuzhou** [comment]
Mitchell-Lee-93
Of course I will,but I have a question,if you test the 00 sequence with only lidar data,the IMU part in the lego-loam should be deleted,isn't it?

**Comment by xuwuzhou** [comment]
Hello,Mitchell-Lee-93
Of course I will,but I have a question,if you test the 00 sequence with only lidar data,the IMU part in the lego-loam should be deleted,isn't it?

**Comment by Mitchell-Lee-93** [comment]
you can play only Velodyne topic with "rosbag play *.bag --clock --topic /kitti/velo/pointcloud" 
(It differs by your bag file's topic name)

**Comment by xuwuzhou** [comment]
Thanks for your reply!
I know what you mean,but I wonder that  if there is no IMU data put in, the IMU part in the source code will  stay static when running the repo(=if the IMU part infuence the final result without IMU data in).

**Comment by xuwuzhou** [comment]
Hello, @Mitchell-Lee-93 
Just now,I tested the repo with 00 sequence without IMU(use the kittibag which you provided to generate a bag),but the result is worse:
![图片](https://user-images.githubusercontent.com/44218507/71720381-80250480-2e5c-11ea-96af-d01be3c9031b.png)
Your result is really good ,just with a little bias;
the tools is kittibag,and directory structrue is as follows:
![图片](https://user-images.githubusercontent.com/44218507/71720502-f164b780-2e5c-11ea-990c-9957bd736aaa.png)
and I have change the params in the launch file:
![图片](https://user-images.githubusercontent.com/44218507/71720547-16f1c100-2e5d-11ea-808b-19e6955d9468.png)
After that ,I run the repo,and I play the bag with order "rosbag play 00.bag --clock".
Do you know where I made a mistake?
Best regards!

**Comment by Mitchell-Lee-93** [comment]
Did you maybe speed up the rosbag play factor with "rosbag play -r" command? I tried to speed up the topic with it, but I got a distorted trajectory like yours. If it's not the problem, I'm not sure what's the problem for now

**Comment by xuwuzhou** [comment]
Hello @Mitchell-Lee-93 
I didn't speed up the rosbag play factor;
And when I play the bag which the kittibag generated,something wrong happens to the rviz:
![图片](https://user-images.githubusercontent.com/44218507/71727358-f7ff2900-2e74-11ea-87f2-8c99f74ab55e.png)
but in fact it can put out result in result.txt as mentioned;
Just now,the author of lego-loam replied that the comment which he made in issue#12 isn't right,do you know what should be changed?
![图片](https://user-images.githubusercontent.com/44218507/71727497-66dc8200-2e75-11ea-90e6-688f76f49211.png)

**Comment by xuwuzhou** [comment]
Just now,I used the tool "kitti2bag" to generate a bag through raw data,
and use the order"play **.bag --clock --topic --topic /kitti/velo/pointcloud"
the result didn't get better:
![图片](https://user-images.githubusercontent.com/44218507/71728717-cdaf6a80-2e78-11ea-9efa-dcefe39e6476.png)
it seems that with or without the order"--topic /kitti/velo/pointcloud" don't make any change,
But your result is really good ,do you make any change on the source code?

**Comment by Mitchell-Lee-93** [comment]
I believe since kittibag doesn't generate TF topic, it's like that only when you use Rviz but result is still same. And for --topic, if you've used kittibag, there is no IMU topic so it's normal that there is no difference.  For the difference of the result, would you try my kitti-A-loam repository? Since it's using optimization, I guess the results might be a bit different from computer to computer. If you get different result of my kitti-A-loam result, that might be the problem

**Comment by xuwuzhou** [comment]
Thanks for your reply;
Yesterday,I tried your kitti-A-loam,the result is same as you ;
I know what happened;
Because I used raw data to generate a bag before,after I used the distorted data,the result gets better

**Comment by Mitchell-Lee-93** [comment]
It's good to know that you've solved the problem!
