### ISSUE TITLE
Cannot visualize the results in RVIZ and There's no tf data

### ISSUE THREAD

**Issue by mhaboali** [Mitchell-Lee-93/kitti-lego-loam#3]
I can not run your package with KITTI odometry data. I did with A-LOAM and it worked perfectly.

Please let me know if you can guide me on how to run your package with KITTI. 

Thanks!

**Comment by Mitchell-Lee-93** [comment]
Would you give me more details? I can't find what is the problem for now

**Comment by lionelyu** [comment]
@Mitchell-Lee-93 
I have a similar problem as @mhaboali.
First, I can not make rosbag with your code. See detail below.
![image](https://user-images.githubusercontent.com/37662833/80856586-d88ad800-8c7d-11ea-9912-da1116b4d8f2.png)

Second, when I use my own rosbag which has already been tested with LOAM. During and after I play the rosbag,  there is simply no visualization result in RVIZ and also no tf data in the result_path that I configure in the run.launch file.

I did everything exactly as your instruction.

**Comment by lionelyu** [comment]
![image](https://user-images.githubusercontent.com/37662833/80856736-fa388f00-8c7e-11ea-8456-8ca534c5b0a3.png)

As you can see above, both  **roslaunch lego_loam run.launch** and **rosbag play *.bag --clock**  works fine. But there is simply no visualization in RVIZ and also no output tf data in my result_path.

**Comment by Mitchell-Lee-93** [comment]
@mhaboali @lionelyu Modified the 3rd line of kittibag.launch to
![image](https://user-images.githubusercontent.com/56542570/82902161-0374fd00-9f9a-11ea-9c1f-e7389a5322d9.png)
please let me know if the error still occurs
