### ISSUE TITLE
result of kitti sequence 00 and 10 is worse than A-LOAM

### ISSUE THREAD

**Issue by cgbcgb** [Mitchell-Lee-93/kitti-lego-loam#4]
I run your code in kitti sequence 00 and 10, I found the result was worse than A-LOAM
how about your result?

![Screenshot from 2020-04-26 09-49-26](https://user-images.githubusercontent.com/26104888/80300886-eef2e880-87d2-11ea-9e38-0c72be898acc.png)
![Screenshot from 2020-04-26 09-50-56](https://user-images.githubusercontent.com/26104888/80300892-f74b2380-87d2-11ea-957a-dd1fd2b543c9.png)
the white trajectory is groundtruth, and the worse trajectory is produced by lego-loam, the better trajectory is produced by A-LOAM

**Comment by Mitchell-Lee-93** [comment]
From my experience, generally, A-loam had better performance compared to the LeGO loam with Kitti data set
