### ISSUE TITLE
rosdep install --from-paths src --ignore-src -r -y

### ISSUE THREAD

**Issue by bryantaoli** [Mitchell-Lee-93/kitti-lego-loam#5]
Why you need to do: rosdep install --from-paths src --ignore-src -r -y?

**Comment by Mitchell-Lee-93** [comment]
It is used to install dependencies of all packages. Sometimes dependency problems still occur even after installing independent dependencies. So I just wanted to double-check it with the command.

**Comment by bryantaoli** [comment]
And the other question is, after I ran roslaunch kittibag kittibag.launch, i get the error bellow
![image](https://user-images.githubusercontent.com/30526360/80793236-27c30100-8bc9-11ea-90ce-7fd9303ef2db.png)

**Comment by lionelyu** [comment]
@bryantaoli 
I got exactly the same problem for making rosbag. 
Have you found the solution?
Also, I can use other tools to make rosbag from kitti dataset and that rosbag works fine for LOAM. So does it also work for Lego-LOAM?

**Comment by bryantaoli** [comment]
> @bryantaoli
> I got exactly the same problem for making rosbag.
> Have you found the solution?
> Also, I can use other tools to make rosbag from kitti dataset and that rosbag works fine for LOAM. So does it also work for Lego-LOAM?
No, this repository is not work for me now.

**Comment by Mitchell-Lee-93** [comment]
@bryantaoli  Modified the 3rd line of kittibag.launch to
![image](https://user-images.githubusercontent.com/56542570/82902268-2a333380-9f9a-11ea-9078-25de66114ed9.png)
please let me know if the error still occurs

**Comment by bryantaoli** [comment]
> @bryantaoli Modified the 3rd line of kittibag.launch to
> ![image](https://user-images.githubusercontent.com/56542570/82902268-2a333380-9f9a-11ea-9078-25de66114ed9.png)
> please let me know if the error still occurs

Thank you, it works!

**Comment by Mitchell-Lee-93** [comment]
That's good to hear!
