### ISSUE TITLE
Can not make bagfile from kitti

### ISSUE THREAD

**Issue by s271** [Mitchell-Lee-93/kitti-lego-loam#6]
I'm getting error
ERROR: cannot launch node of type [aloam_velodyne/kittiHelper]: aloam_velodyne
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/sergey/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share

rospack find kittibag
finding package at /home/sergey/catkin_ws/src/kittibag

kittibag launh:
<launch>
    
    <node name="kittiHelper" pkg="aloam_velodyne" type="kittiHelper" output="screen"> 
        <param name="dataset_folder" type="string" value="/home/sergey/Downloads/dataset_vl/" />
        <param name="sequence_number" type="string" value="10" />
        <param name="to_bag" type="bool" value="true" />
        <param name="output_bag_file" type="string" value="/home/sergey/aux_workspace/output_lego/10.bag" /> 
        <param name="publish_delay" type="int" value="1" />
    </node>
</launch>

Logfile:
[roslaunch-sergey-PC-9863.log](https://github.com/Mitchell-Lee-93/kitti-lego-loam/files/4587137/roslaunch-sergey-PC-9863.log)

I've installed ROS melodic, ubuntu 18
Thanks

**Comment by s271** [comment]
Script based on kitti2bag works as replacement

**Comment by Mitchell-Lee-93** [comment]
Would you give me more details about the replacement?
