### ISSUE TITLE
'std::bad_alloc'  error

### ISSUE THREAD

**Issue by hyxhope** [Mitchell-Lee-93/kitti-lego-loam#7]
I've got an error. Here is the detail.

process[kittiHelper-1]: started with pid [16242]
Reading sequence 07 from /home/hyx/data/
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[kittiHelper-1] process has died [pid 16242, exit code -6, cmd /home/hyx/catkin_ws/devel/lib/aloam_velodyne/kittiHelper __name:=kittiHelper __log:=/home/hyx/.ros/log/192ad190-92bd-11ea-b4a1-b025aa15cdd2/kittiHelper-1.log].
log file: /home/hyx/.ros/log/192ad190-92bd-11ea-b4a1-b025aa15cdd2/kittiHelper-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

I 've run the demo in Ubuntu 16.04.
Thanks a lot.

**Comment by Mitchell-Lee-93** [comment]
I've modified some codes. Clean your catkin space and try with the new code and let me know how did it go

**Comment by hyxhope** [comment]
Thanks for your reply. 
A few days ago, I've tried the code in Ubuntu18.04 and it could run well. 
Maybe the gcc-version in ubuntu16.06 didn't fit your code so that the problem came out.
In any case,  your code did help me a lot, and I'll give u a star.
Thank you.

**Comment by Mitchell-Lee-93** [comment]
The clear reason for the error is hard to tell since I've never seen that error but that makes sense. It's good to know that it worked and helped you a lot. Thank you for the star!
