### ISSUE TITLE
Failed to find match for field 'ring'.

### ISSUE THREAD

**Issue by bryantaoli** [Mitchell-Lee-93/kitti-lego-loam#8]
When I ran your code, I got that 
Failed to find match for field 'ring'.
![image](https://user-images.githubusercontent.com/30526360/82743609-42d7f980-9da0-11ea-9d91-58b8a14417f8.png)

**Comment by Mitchell-Lee-93** [comment]
I believe there is a problem with the bag file. Check the changed kittibag.launch and try with the new bagfile

**Comment by bryantaoli** [comment]
> I believe there is a problem with the bag file. Check the changed kittibag.launch and try with the new bagfile

Now, I can run the lego_loam on Kitti, thank you, but I still don't know why the error above happened

**Comment by Mitchell-Lee-93** [comment]
That's good! I'm not sure about the clear reason, but this kind of error can occur when the bag file doesn't have the components needed for the program.
