### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emi0116** [Mitchell-Lee-93/kitti-lego-loam#9]
Hello！

Thank you for a great job！

I would like to use your code.
What is the license for this code?

**Comment by Mitchell-Lee-93** [comment]
Hello!
Thank you for pointing out about the license. I have uploaded the license file.
It has the same license with original  LeGO-LOAM which means you are free to 
modify, distribute, and use it as both commercial and private usage.

**Comment by emi0116** [comment]
Thank you for your quick reply.
